
MACRO(LibChaos_Configure_Target TARGET)
    SET_PROPERTY(TARGET ${TARGET} PROPERTY CXX_STANDARD 14)
    SET_PROPERTY(TARGET ${TARGET} PROPERTY CXX_STANDARD_REQUIRED 11)
    SET_PROPERTY(TARGET ${TARGET} PROPERTY COMPILE_FLAGS ${LIBCHAOS_CXX_FLAGS})
    TARGET_LINK_LIBRARIES(${TARGET} chaos)
ENDMACRO()
