
FUNCTION(GatherSources)
    GET_PROPERTY(LibChaosAllSources GLOBAL PROPERTY LibChaosAllSources)
    FOREACH(SRC ${ARGV})
        SET(LibChaosAllSources ${LibChaosAllSources} ${CMAKE_CURRENT_SOURCE_DIR}/${SRC})
    ENDFOREACH()
    SET_PROPERTY(GLOBAL PROPERTY LibChaosAllSources ${LibChaosAllSources})
ENDFUNCTION()

FUNCTION(GatherIncludes)
    GET_PROPERTY(LibChaosIncludes GLOBAL PROPERTY LibChaosIncludes)
    FOREACH(DIR ${ARGV})
        SET(LibChaosIncludes ${LibChaosIncludes} ${CMAKE_CURRENT_SOURCE_DIR}/${DIR})
    ENDFOREACH()
    SET_PROPERTY(GLOBAL PROPERTY LibChaosIncludes ${LibChaosIncludes})
ENDFUNCTION()
